#!/usr/bin/env bash

readonly NVIM_DATA_DIR="${XDG_DATA_HOME:-${HOME}/.local/share}/nvim"
readonly NVIM_CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/nvim"
readonly NVIM_CONFIG_SRC_DIR="${DFILES_CONFIGS_DIR}/nvim"

__dfiles_log "Downloading and installing the latest Neovim AppImage..."
__dfiles_run_cmd curl -sLO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
__dfiles_run_cmd chmod u+x nvim-linux-x86_64.appimage
__dfiles_run_cmd sudo mv -v nvim-linux-x86_64.appimage /usr/local/bin/nvim

__dfiles_log "Neovim installed, applying configuration..."
__dfiles_run_cmd rm -rf "${NVIM_DATA_DIR}" "${NVIM_CONFIG_DIR}" || true
__dfiles_run_cmd mkdir -pv "${NVIM_CONFIG_DIR}"
__dfiles_run_cmd cp -rv "${NVIM_CONFIG_SRC_DIR}"/. "${NVIM_CONFIG_DIR}"
__dfiles_log "Neovim setup and configuration completed successfully."
