#!/usr/bin/env bash

curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash

# Example usages from documentation (https://github.com/nvm-sh/nvm#intro):
#
#   $ nvm install 24
#   Now using node v24.14.0 (npm v11.9.0)
#   $ node -v
#   v24.14.0
#   $ nvm use 22
#   Now using node v22.22.1 (npm v10.9.4)
#   $ node -v
#   v22.22.1
#   $ nvm use 20
#   Now using node v20.20.1 (npm v10.8.2)
#   $ node -v
#   v20.20.1
