#!/usr/bin/env bash

readonly SDKMAN_CONFIG_DIR="${HOME}/.sdkman"
readonly SDKMAN_INIT_SCRIPT="${SDKMAN_CONFIG_DIR}/bin/sdkman-init.sh"

__dfiles_log "Installing SDKMAN!..."
__dfiles_run_cmd rm -rfv "${SDKMAN_CONFIG_DIR}" || true
__dfiles_run_cmd bash -c 'curl -s "https://get.sdkman.io" | bash' &>/dev/null

set +u
__dfiles_run_cmd source "${SDKMAN_INIT_SCRIPT}"
set -u

__dfiles_log "Installation completed successfully for SDKMAN!"
