#!/usr/bin/env bash

readonly tmux_config_dir="${XDG_CONFIG_HOME:-${HOME}/.config}/tmux"
readonly tmux_config_src_dir="${DFILES_CONFIGS_DIR}/tmux"

sudo apt-get install -yqq tmux
mkdir -pv "${tmux_config_dir}/plugins"
ln -sv "${tmux_config_src_dir}/tmux.conf" "${tmux_config_dir}/tmux.conf"

# Clone tpm (tmux plugin manager) and install plugins
if [[ ! -d "${tmux_config_dir}/plugins/tpm" ]]; then
  echo "Tmux plugin manager not found; cloning it from GitHub into plugins directory..."
  git clone https://github.com/tmux-plugins/tpm "${tmux_config_dir}/plugins/tpm"
else
  echo "Tmux plugin manager already installed; skipping clone..."
fi

echo "Installing tmux plugins..."
"${tmux_config_dir}/plugins/tpm/bin/install_plugins"
echo "Tmux installation completed successfully."
